[package]
name = "remo-store"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
env_logger = "0.11.6"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde_json = "1.0.142"
